application: giftyapp-hrd
version: 4
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /frame
  static_dir: frame

- url: /lib
  static_dir: lib

- url: /.*
  script: controllers/gifty.py



